# YAML file
# constrints: all the variables in function shold have "," after the value eg:- (var=val,)
#In cnn: model.fit must be stored in a variable and the variable name must be written here in ModelFitVariable 


RepoURL: https://github.com/gautamnankani/ML_project.git
RepoName: ML_project

Name: First_model
Kind: CNN
Counter: 2
AccuracyVariable: accuracy
HyperParameter:
  HYP1:
     filters: [32,64]
  HYP2:
     filters: [32,64]
  HYP2:
     units: [128,256]
